name: build-blobtoolkit-dependencies

on:
  push:
  workflow_call:

jobs:
  build-blobtoolkit-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Collect artifacts
        uses: actions/download-artifact@v3
        with:
          path: ./dist
      - name: Move artifacts
        run: |
          mv dist/node/*-linux src/docker/dependencies/ || true
      - name: Move pip artifacts
        run: |
          mv dist/pip/*-*-*linux*.whl src/docker/dependencies/ || true
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: genomehubs/blobtoolkit-dependencies
      - name: Set current date as env variable
        id: date
        run: echo "today=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
      - name: Set docker tags
        id: tags
        run: echo "docker=genomehubs/blobtoolkit-dependencies:${{ steps.date.outputs.labels }},genomehubs/blobtoolkit-dependencies:latest" >> $GITHUB_OUTPUT
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: src/docker/dependencies
          build-args: VERSION=${{ steps.date.outputs.labels }}
          push: true
          tags: ${{ steps.tags.outputs.docker }}
          labels: ${{ steps.meta.outputs.labels }}
